package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	const (
		providerSourceDir       = "/Users/rohabhat/Documents/work/code/go/src/github.com/oracle/terraform-provider-oci/provider"
		outputOfProviderParsing = "./providerCode.out"

		autoGenSourceDir           = "/Users/rohabhat/Documents/work/code/go/src/github.com/oracle/terraform-code-gen/outputFiles/privateIps/terraform-provider-oci/provider"
		outputOfAutoGenCodeParsing = "./autoGenCode.out"
	)

	processProviderCode(providerSourceDir, outputOfProviderParsing)

	processAutoGeneratedCode(autoGenSourceDir, outputOfAutoGenCodeParsing)
}

func processProviderCode(providerSourceDir string, outputOfProviderParsing string) {
	outFile, err := os.Create(outputOfProviderParsing)
	if err != nil {
		panic("Could not create output file for provider code analysis")
	}

	files, err := ioutil.ReadDir(providerSourceDir)
	if err != nil {
		panic("Could not read source directory")
	}

	var funcNamesWithSchemaDefs = readProviderForFuncNamesWithSchemaDefs(providerSourceDir)

	for _, file := range files {
		if file.IsDir() {
			continue
		}

		if !isResourceFile(file.Name()) && !isDataSourceFile(file.Name()) {
			continue
		}

		filePath := fmt.Sprintf("%s/%s", providerSourceDir, file.Name())

		outFile.WriteString(fmt.Sprintf("File: %s:\n", file.Name()))

		writeSchema(filePath, funcNamesWithSchemaDefs, outFile)

		outFile.WriteString("\n")
	}
}

func processAutoGeneratedCode(autoGenSourceDir string, outputOfAutoGenCodeParsing string) {
	outFile, err := os.Create(outputOfAutoGenCodeParsing)
	if err != nil {
		panic("Could not create output file for provider code analysis")
	}

	files, err := ioutil.ReadDir(autoGenSourceDir)
	if err != nil {
		panic("Could not read source directory")
	}

	for _, file := range files {
		if file.IsDir() {
			continue
		}

		if !isResourceFile(file.Name()) && !isDataSourceFile(file.Name()) {
			continue
		}

		filePath := fmt.Sprintf("%s/%s", autoGenSourceDir, file.Name())
		funcName := findFuncNameWithSchemaDefsInAutoGenCode(filePath)

		outFile.WriteString(fmt.Sprintf("File: %s:\n", file.Name()))

		writeSchema(filePath, map[string]bool{funcName: true}, outFile)

		outFile.WriteString("\n")
	}
}
